### ISSUE TITLE
Tutorial on how to edit jupyterbook

### ISSUE THREAD

**Issue by npr99** [npr99/IN-CORE_Galveston#7]
What are the steps for editing the jupyterbook?

**Comment by npr99** [comment]
@Kooshan1 - if we setup a meeting I can make a Zoom Recording that walks through all of the steps.

**Comment by npr99** [comment]
link to jupyterbook:
https://npr99.github.io/IN-CORE_Galveston/intro.html

**Comment by Kooshan1** [comment]
@npr99 Sorry I didn't notice your message that day. I am ready to have the mentioned meeting or even make a short document to simply add new notebooks to the Jupyter Book of Galveston Testbed. Kindly let me know.

**Comment by npr99** [comment]
Hi Kooshan
Trying out replying to an issue through my email.
What time works for you ?

**Comment by Kooshan1** [comment]
@npr99 It actually brings all the unnecessary messages if you check your comment on Git Hub!
I am free this Friday anytime after 12 pm. Please schedule a meeting if that works for you.
